### ISSUE TITLE
Not working on Marshmallow

### ISSUE THREAD

**Issue by iAbadyR** [ultramancool/AudioPrivacy#13]
It doesn't work in my nexus 6p with Android version 6.0.1

**Comment by Mick2011** [comment]
Any plans to make this mm compatible?

**Comment by ultramancool** [comment]
We should currently be marshmallow compatible with most media players - it successfully blocks Spotify, Pocket Casts and DI.fm players at least. I have noticed a potential issue with YouTube in the background though. 

Be aware though that on Lollipop and newer we only block Album Art in the background of the lock screen - you need to set the notifications for your media player as private if you want to hide them on the lock screen. 

If you have any specific players with issues let me know and I'll give them a try. Bonus points for open source ones which might point me at APIs which I need to hook still. Otherwise I have to delve into reverse engineering them.

**Comment by ultramancool** [comment]
Latest version should resolve any standing issues with different players.
